# @changelog docker compose anchor tag examples

version: "3.6"

x-base-server:
  server: &base_server
    image: busybox:latest
    environment:
      - HOST=localhost
      - PORT=8080
    ports:
      - 80:80

x-base-env:
  foo-environment: &env_common  
    - HOST=localhost
    - PORT=8080
    - EXTRA_CONFIG=foo/bar.conf
  bar-environment: &env_common_bar  
    HOST: localhost
    PORT: 8080
    EXTRA_CONFIG: foo/bar.conf

services:
  server:
    <<: *base_server
    container_name: server.hoojo.com
    hostname: dev-server
    # overwrite base_server port
    ports:
      - 8082:80
    # array type  
    environment: *env_common
    
  client:
    image: busybox:latest
    environment: 
      # object type
      <<: *env_common_bar
      
      # error, array type not support append or override
      #- CUSTOM_ENV=append/env.conf
      
      # success, object type support append & overwrite
      CUSTOM_ENV: append/env.conf
       
      
