# @changelog Added docker compose multiple files assess httpd service example

version: "3"

services:

  java_app:
    image: hoojo/jib-hello:1.0
    container_name: java_app
    hostname: app.local
    domainname: hoojo.com
    
    network_mode: "host"
    environment:
      # ports 8080 access successful, expose 80 access failure.
      - ENV_REQUEST_URL=http://localhost:80/,http://localhost:8080/,http://192.168.99.100:8080/
    
  shell_app:
    image: busybox:latest
    container_name: shell_app
    hostname: app.local
    domainname: hoojo.com
    tty: true
    stdin_open: true     
    
    network_mode: "host"
    environment:
      # ports 8080 access successful, expose 80 access failure.
      - ENV_REQUEST_URL=http://localhost:80/,http://localhost:8080/,http://192.168.99.100:8080/
    volumes:
      - "/mnt/docker-container-httpd/test-scripts:/test-scripts:ro"
    command: "sh -c ./test-scripts/test.sh"  