version: '3.6'

#-----------------------------------------------------------------------------------
# base service yaml
#-----------------------------------------------------------------------------------
x-base-services:
  zookeeper: &zookeeper-base
    image: hyperledger/fabric-zookeeper${IMAGE_TAG_FABRIC_ZOOKEEPER}
    restart: always
    expose:
      - 2181
      - 2888
      - 3888

  kafka: &kafka-base
    image: hyperledger/fabric-kafka${IMAGE_TAG_FABRIC_KAFKA}
    restart: always
    environment: &kafka-env-common
      KAFKA_MESSAGE_MAX_BYTES: 103809024 # 99 * 1024 * 1024 B
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024 # 99 * 1024 * 1024 B
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_MS: -1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    expose:
      - 9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2


#-----------------------------------------------------------------------------------
# kafka & zookeeper networks yaml
#-----------------------------------------------------------------------------------
networks:
  net:
    external:
      name: orderer-zk-net

#-----------------------------------------------------------------------------------
# kafka & zookeeper service yaml
#-----------------------------------------------------------------------------------
services:
  zookeeper0:
    container_name: zookeeper0
    hostname: zookeeper0.example.com
    <<: *zookeeper-base
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      net:
        aliases:
        - zookeeper0.example.com

  zookeeper1:
    container_name: zookeeper1
    hostname: zookeeper1.example.com
    <<: *zookeeper-base
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      net:
        aliases:
        - zookeeper1.example.com

  zookeeper2:
    container_name: zookeeper2
    hostname: zookeeper2.example.com
    <<: *zookeeper-base
    environment:
      ZOO_MY_ID: 3  
      ZOO_SERVERS: server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      net:
        aliases:
        - zookeeper2.example.com

  kafka0:
    container_name: kafka0
    hostname: kafka0.example.com
    <<: *kafka-base
    environment:
      <<: *kafka-env-common
      KAFKA_BROKER_ID: 0
    networks:
      net:
        aliases:
        - kafka0.example.com
  
  kafka1:
    container_name: kafka1
    hostname: kafka1.example.com
    <<: *kafka-base
    environment:
      <<: *kafka-env-common
      KAFKA_BROKER_ID: 1
    networks:
      net:
        aliases:
        - kafka1.example.com
 
  kafka2:
    container_name: kafka2
    hostname: kafka2.example.com
    <<: *kafka-base
    environment:
      <<: *kafka-env-common
      KAFKA_BROKER_ID: 2
    networks:
      net:
        aliases:
        - kafka2.example.com
 
  kafka3:
    container_name: kafka3
    hostname: kafka3.example.com
    <<: *kafka-base
    environment:
      <<: *kafka-env-common
      KAFKA_BROKER_ID: 3
    networks:
      net:
        aliases:
        - kafka3.example.com