version: "3.6"

services:
  server:
    tty: true
    stdin_open: true
    environment:
      - HOST=localhost
      - PORT=8080
    ports:
      - 8080:80  
    
  app:
    image: busybox:latest
    container_name: app.com
    hostname: dev-app
    domainname: app.hoojo.com
    ports:
      - 80:80
