# @changelog Added docker compose external assess httpd service example

version: "3"

services:

  httpd:
    image: httpd
    container_name: httpd_service
    hostname: app.local
    domainname: hoojo.com
    ports:
      - 80:80
      - 8080:80