# @changelog Added docker swarm external assess httpd service example

version: "3.6"

services:

  external_httpd:
    image: httpd
    container_name: external_httpd_service
    ports:
      - 80:80
      - 8080:80
      
  internal_httpd:
    image: httpd
    container_name: internal_httpd_service
    expose:
      - 80
      
  java_app:
    image: hoojo/jib-hello:1.0
    container_name: java_app
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        
    environment:
      # SERVICE NAME
      # http://external_httpd:8080 access failure, Connect to external_httpd:8080 [external_httpd/172.22.0.2] failed: Connection refused
      # port 80 access successful
      #- ENV_REQUEST_URL=http://external_httpd:80/,http://external_httpd:8080/,http://internal_httpd:80/
      #- ENV_REQUEST_URL=http://tasks.external_httpd:80/,http://tasks.external_httpd:8080/,http://tasks.internal_httpd:80/
      #- ENV_REQUEST_URL=http://ext_external_httpd:80/,http://ext_external_httpd:8080/,http://ext_internal_httpd:80/
      - ENV_REQUEST_URL=http://tasks.ext_external_httpd:80/,http://tasks.ext_external_httpd:8080/,http://tasks.ext_internal_httpd:80/
      
      
  shell_app:
    image: busybox:latest
    container_name: shell_app
    tty: true
    stdin_open: true     
    
    environment:
      # SERVICE NAME
      #- ENV_REQUEST_URL=http://external_httpd:80/,http://external_httpd:8080/,http://internal_httpd:80/
      #- ENV_REQUEST_URL=http://tasks.external_httpd:80/,http://tasks.external_httpd:8080/,http://tasks.internal_httpd:80/
      #- ENV_REQUEST_URL=http://ext_external_httpd:80/,http://ext_external_httpd:8080/,http://ext_internal_httpd:80/
      - ENV_REQUEST_URL=http://tasks.ext_external_httpd:80/,http://tasks.ext_external_httpd:8080/,http://tasks.ext_internal_httpd:80/

    volumes:
      - "/mnt/docker-swarm-httpd/test-scripts:/test-scripts:ro"
    command: "sh -c ./test-scripts/test.sh"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3  