# @changelog Added docker compose singel file assess httpd service example

version: "3"

services:

  external_httpd:
    image: httpd
    container_name: external_httpd_service
    ports:
      - 80:80
      - 8080:80
      
  internal_httpd:
    image: httpd
    container_name: internal_httpd_service
    expose:
      - 80
      
  shell_app:
    image: busybox:latest
    container_name: shell_app
    tty: true
    stdin_open: true      
    
    links:
      - external_httpd:external
      - internal_httpd:internal
    environment:
      # access failure, Connection refused 
      #- ENV_REQUEST_URL=http://external:8080/,http://external_httpd:8080/,http://external_httpd_service:8080/
      
      # access successful
      #- ENV_REQUEST_URL=http://external:80/,http://external_httpd:80/,http://external_httpd_service:80/

      # access successful
      - ENV_REQUEST_URL=http://internal:80/,http://internal_httpd:80/,http://internal_httpd_service:80/
    volumes:
      - "/mnt/docker-container-httpd/test-scripts:/test-scripts:ro"
    command: "sh -c ./test-scripts/test.sh" 
    
        
  java_app:
    image: hoojo/jib-hello:1.0
    container_name: java_app
    
    links:
      - external_httpd:external
      - internal_httpd:internal
    volumes:
      - /var/log4j:/var/log4j  
    environment:
      # access failure, Connection refused, 
      #- ENV_REQUEST_URL=http://external:8080/,http://external_httpd:8080/,http://external_httpd_service:8080/
      
      # access success, successfully routed
      #- ENV_REQUEST_URL=http://external:80/,http://external_httpd:80/,http://external_httpd_service:80/
      
      # access success
      - ENV_REQUEST_URL=http://internal:80/,http://internal_httpd:80/,http://internal_httpd_service:80/
    
  