# @changelog Added docker swarm default network service example

version: "3.6"

services:

  java_app:
    image: hoojo/jib-hello:1.0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      # access failure
      #- ENV_REQUEST_URL=http://external:80/,http://external:8080/,http://internal:80/
      # Name does not resolve
      #- ENV_REQUEST_URL=http://tasks.external:80/,http://tasks.external:8080/,http://tasks.internal:80/
      # Name does not resolve
      #- ENV_REQUEST_URL=http://provider_external:80/,http://provider_external:8080/,http://provider_internal:80/
      # Name does not resolve
      - ENV_REQUEST_URL=http://tasks.provider_external:80/,http://tasks.provider_external:8080/,http://tasks.provider_internal:80/
    
  shell_app:
    image: busybox:latest
    tty: true
    stdin_open: true      
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      # failure
      #- ENV_REQUEST_URL=http://external:80/,http://external:80/,http://internal:80/
      # wget: bad address
      #- ENV_REQUEST_URL=http://tasks.external:80/,http://tasks.external:8080/,http://tasks.internal:80/
      # wget: bad address
      #- ENV_REQUEST_URL=http://provider_external:80/,http://provider_external:8080/,http://provider_internal:80/
      # wget: bad address
      - ENV_REQUEST_URL=http://tasks.provider_external:80/,http://tasks.provider_external:8080/,http://tasks.provider_internal:80/
      
    volumes:
      - "/mnt/docker-swarm-httpd/test-scripts:/test-scripts:ro"
    command: "sh -c ./test-scripts/test.sh" 