# @changelog Added docker swarm network alias name service example

version: "3.6"

networks:
  net:
    driver: overlay
    attachable: true

services:

  external_httpd:
    image: httpd
    container_name: external_httpd_service
    ports:
      - 80:80
      - 8080:80
    networks:
      net:
        aliases:
         - external-a
         - external-b  
      
  internal_httpd:
    image: httpd
    container_name: internal_httpd_service
    expose:
      - 80
    networks:
      net:
        aliases:
         - internal