# @changelog Added docker compose based service example

version: "3"

services:

  external_httpd:
    image: httpd
    container_name: external_httpd_service
    ports:
      - 80:80
      - 8080:80
    networks:
      default:
        aliases:
         - external-a
         - external-b  
      
  internal_httpd:
    image: nginx
    container_name: internal_httpd_service
    expose:
      - 80
    networks:
      default:
        aliases:
         - internal
      
  java_app:
    image: hoojo/jib-hello:1.0
    container_name: java_app
    
    networks:
      - default
    environment:
      # internal access failure, ERROR -> request failure, status: 405
      # external-* access successful
      - ENV_REQUEST_URL=http://external-b:80/,http://external-a:80/,http://internal:80/
    
  shell_app:
    image: busybox:latest
    container_name: shell_app
    tty: true
    stdin_open: true      
    
    networks:
      - default
    environment:
      - ENV_REQUEST_URL=http://external-b:80/,http://external-a:80/,http://internal:80/
    volumes:
      - "/mnt/docker-container-httpd/test-scripts:/test-scripts:ro"
    command: "sh -c ./test-scripts/test.sh" 