# @changelog Added docker compose external assess httpd service example

version: "3"

services:

  external_httpd:
    image: httpd
    container_name: external_httpd_service
    hostname: httpd.local
    domainname: hoojo.com
    ports:
      - 80:80
      - 8080:80
      
  internal_httpd:
    image: httpd
    container_name: internal_httpd_service
    hostname: httpd.local
    domainname: hoojo.com
    expose:
      - 80
      
  java_app:
    image: hoojo/jib-hello:1.0
    container_name: java_app
    hostname: app.local
    domainname: hoojo.com
    
    environment:
      # http://external_httpd:8080 access failure, 由于是内部调用，只能访问内部的接口，而不是指向外部的接口
      - ENV_REQUEST_URL=http://external_httpd:80/,http://external_httpd:8080/,http://internal_httpd:80/
      
  shell_app:
    image: busybox:latest
    container_name: shell_app
    hostname: app.local
    domainname: hoojo.com
    tty: true
    stdin_open: true      