# @changelog Added docker singel compose external assess httpd service example

version: "3"

services:

  external_httpd:
    image: httpd
    container_name: external_httpd_service
    hostname: httpd.local
    domainname: hoojo.com
    ports:
      - 80:80
      - 8080:80
      
  java_app:
    image: hoojo/jib-hello:1.0
    container_name: java_app_service
    hostname: app.local
    domainname: hoojo.com
    
    environment:
      # not access url
      #- ENV_REQUEST_URL=http://localhost:80/,http://localhost:8080/
      - ENV_REQUEST_URL=http://192.168.99.100:80/,http://192.168.99.100:8080/
          
  shell_app:
    image: busybox:latest
    container_name: shell_app_service
    hostname: app.local
    domainname: hoojo.com
    tty: true
    stdin_open: true      