# @changelog Added docker compose external assess httpd service example

version: "3"

services:

  external_httpd:
    image: httpd
    container_name: external_httpd_service
    hostname: httpd.local
    domainname: hoojo.com
    ports:
      - 80:80
      - 8080:80
      
  internal_httpd:
    image: httpd
    container_name: internal_httpd_service
    hostname: httpd.local
    domainname: hoojo.com
    expose:
      - 80
      
  shell_app:
    image: busybox:latest
    container_name: shell_app
    hostname: app.local
    domainname: hoojo.com
    tty: true
    stdin_open: true      
    
    links:
      - internal_httpd:external
      - internal_httpd:internal
      
    environment:
      - ENV_REQUEST_URL=http://external:80/,http://internal:80/,http://external_httpd:80/,http://internal_httpd:80/
    volumes:
      - "/mnt/docker-container-httpd/test-scripts:/test-scripts:ro"
    command: "sh -c ./test-scripts/test.sh" 
    
        
  java_app:
    image: hoojo/jib-hello:1.0
    container_name: java_app
    hostname: app.local
    domainname: hoojo.com
    
    links:
      - internal_httpd:external
      - internal_httpd:internal
      
    environment:
      # service alias access success.
      - ENV_REQUEST_URL=http://external:80/,http://internal:80/,http://external_httpd:80/,http://internal_httpd:80/
    
  