# @changelog Added docker compose external assess httpd service example

version: "3"

services:

  external_httpd:
    image: httpd
    container_name: external_httpd_service
    hostname: httpd.local
    domainname: hoojo.com
    ports:
      - 80:80
      - 8080:80
      
  internal_httpd:
    image: httpd
    container_name: internal_httpd_service
    hostname: httpd.local
    domainname: hoojo.com
    expose:
      - 80
      
  java_app:
    image: hoojo/jib-hello:1.0
    container_name: java_app
    hostname: app.local
    domainname: hoojo.com
    
    environment:
      # SERVICE NAME
      # http://external_httpd:8080 access failure, Connect to external_httpd:8080 [external_httpd/172.22.0.2] failed: Connection refused
      # port 80 access successful
      #- ENV_REQUEST_URL=http://external_httpd:80/,http://external_httpd:8080/,http://internal_httpd:80/
      
      # CONTAINER NAME
      # access successful 
      - ENV_REQUEST_URL=http://internal_httpd_service:80/,http://internal_httpd_service:80/
      
  shell_app:
    image: busybox:latest
    container_name: shell_app
    hostname: app.local
    domainname: hoojo.com
    tty: true
    stdin_open: true     
    
    environment:
      # SERVICE NAME
      # wget: server returned error: HTTP/1.1 403 Forbidden
      #- ENV_REQUEST_URL=http://external_httpd:80/,http://external_httpd:8080/,http://internal_httpd:80/

      # CONTAINER NAME
      # wget: server returned error: HTTP/1.1 403 Forbidden
      - ENV_REQUEST_URL=http://internal_httpd_service:80/,http://internal_httpd_service:80/
      
    volumes:
      - "/mnt/docker-container-httpd/test-scripts:/test-scripts:ro"
    command: "sh -c ./test-scripts/test.sh"  