# @changelog Added docker swarm endpoint mode dnsrr service example

version: "3.6"

networks:
  provider-net:
    external: true
    name: provider_net

services:

  java_app:
    image: hoojo/jib-hello:1.0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - provider-net
    environment:
      # access failure
      - ENV_REQUEST_URL=http://external:80/,http://external:8080/,http://internal:80/
      # access inner port(80) successful, 8080 failure: Connection refused (Connection refused)
      #- ENV_REQUEST_URL=http://tasks.external:80/,http://tasks.external:8080/,http://tasks.internal:80/
      # access inner port(80) successful, 8080 failure: Connection refused (Connection refused)
      #- ENV_REQUEST_URL=http://provider_external:80/,http://provider_external:8080/,http://provider_internal:80/
      # access inner port(80) successful, 8080 failure: Connection refused (Connection refused)
      #- ENV_REQUEST_URL=http://tasks.provider_external:80/,http://tasks.provider_external:8080/,http://tasks.provider_internal:80/
    
  shell_app:
    image: busybox:latest
    tty: true
    stdin_open: true      
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - provider-net
    environment:
      # access failure
      - ENV_REQUEST_URL=http://external:80/,http://external:8080/,http://internal:80/
      # access inner port(80) successful, 8080 failure: can't connect to remote host (10.0.0.4): Connection refused
      #- ENV_REQUEST_URL=http://tasks.external:80/,http://tasks.external:8080/,http://tasks.internal:80/
      # access inner port(80) successful, 8080 failure: can't connect to remote host (10.0.0.4): Connection refused
      #- ENV_REQUEST_URL=http://provider_external:80/,http://provider_external:8080/,http://provider_internal:80/
      # access inner port(80) successful, 8080 failure: can't connect to remote host (10.0.0.4): Connection refused
      #- ENV_REQUEST_URL=http://tasks.provider_external:80/,http://tasks.provider_external:8080/,http://tasks.provider_internal:80/
      
    volumes:
      - "/mnt/docker-swarm-httpd/test-scripts:/test-scripts:ro"
    command: "sh -c ./test-scripts/test.sh" 