# @changelog Added docker swarm host access service example

version: "3.6"

services:

  java_app:
    image: hoojo/jib-hello:1.0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      # access success
      - ENV_REQUEST_URL=http://192.168.99.100:80/,http://192.168.99.100:8080/,http://192.168.99.100:80/
    
  shell_app:
    image: busybox:latest
    tty: true
    stdin_open: true      
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - ENV_REQUEST_URL=http://192.168.99.100:80/,http://192.168.99.100:8080/,http://192.168.99.100:80/
      
    volumes:
      - "/mnt/docker-swarm-httpd/test-scripts:/test-scripts:ro"
    command: "sh -c ./test-scripts/test.sh" 