version: '3.6'

x-hosts: &hosts
  - "dev-010:192.168.33.71"
  - "dev-020:192.168.33.72"
  - "dev-030:192.168.33.73"
  - "dev-040:192.168.33.74"

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    deploy:
      placement:
        constraints:
          - node.hostname == dev-010
      restart_policy:
        condition: on-failure
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
      - target: 2888
        published: 2888
        protocol: tcp
        mode: host
      - target: 3888
        published: 3888
        protocol: tcp
        mode: host
    extra_hosts: *hosts
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=dev-020:2888:3888 server.3=dev-040:2888:3888

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    deploy:
      placement:
        constraints:
          - node.hostname == dev-020
      restart_policy:
        condition: on-failure
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
      - target: 2888
        published: 2888
        protocol: tcp
        mode: host
      - target: 3888
        published: 3888
        protocol: tcp
        mode: host
    extra_hosts: *hosts
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=dev-010:2888:3888 server.2=0.0.0.0:2888:3888 server.3=dev-040:2888:3888

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    deploy:
      placement:
        constraints:
          - node.hostname == dev-040
      restart_policy:
        condition: on-failure
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
      - target: 2888
        published: 2888
        protocol: tcp
        mode: host
      - target: 3888
        published: 3888
        protocol: tcp
        mode: host
    extra_hosts: *hosts
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=dev-010:2888:3888 server.2=dev-020:2888:3888 server.3=0.0.0.0:2888:3888
      
  kafka0:
    image: hyperledger/fabric-kafka:x86_64-0.4.6
    deploy:
      placement:
        constraints:
        - node.hostname == dev-010
      restart_policy:
        condition: on-failure
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MESSAGE_MAX_BYTES: 103809024
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: dev-010:2181,dev-020:2181,dev-040:2181
    extra_hosts: *hosts
    ports:
    - target: 9092
    
  kafka1:
    image: hyperledger/fabric-kafka:x86_64-0.4.6
    deploy:
      placement:
        constraints:
        - node.hostname == dev-010
      restart_policy:
        condition: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MESSAGE_MAX_BYTES: 103809024
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: dev-010:2181,dev-020:2181,dev-040:2181
    extra_hosts: *hosts
    ports:
    - target: 9092
    
  kafka2:
    image: hyperledger/fabric-kafka:x86_64-0.4.6
    deploy:
      placement:
        constraints:
        - node.hostname == dev-040
      restart_policy:
        condition: on-failure
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MESSAGE_MAX_BYTES: 103809024
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: dev-010:2181,dev-020:2181,dev-040:2181
    extra_hosts: *hosts
    ports:
    - target: 9092
    
  kafka3:
    image: hyperledger/fabric-kafka:x86_64-0.4.6
    deploy:
      placement:
        constraints:
        - node.hostname == dev-040
      restart_policy:
        condition: on-failure
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MESSAGE_MAX_BYTES: 103809024
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: dev-010:2181,dev-020:2181,dev-040:2181
    extra_hosts: *hosts
    ports:
    - target: 9092
