version: "3"

services:
  redis:
    image: redis
    container_name: redis_cache
    hostname: redis-cache-host
    domainname: cache.com
    networks:
      #- blockchain_net
      blockchain_net:
        aliases:
         - redis-cache-net
         - redis-ache-url
    ports:
      - 6379

  mysql:
    image: busybox
    container_name: mysql_db
    hostname: mysql-db-host
    domainname: db.com
    stdin_open: true
    tty: true
    networks:
      #- db_net
      db_net:
        aliases:
         - mysql-db-net
         - mysql-db-net2
    ports:
      - "8080:8080"

  app:
    image: busybox 
    container_name: my_app
    hostname: app-host
    domainname: app.com
    stdin_open: true
    tty: true
    networks:
      - blockchain_net
      - db_net
    
    depends_on:
      - redis
      - mysql
    links:
      - redis:kv_db
      - mysql:mysql_db
 

    external_links:
      - busybox:box
networks:
  blockchain_net:
  db_net:
#    external:
#      name: fabric_blockchain_net