# @changelog Added docker swarm endpoint_mode dnsrr service example

version: "3.6"

services:
  external_httpd:
    image: httpd
    container_name: external_httpd_service
    deploy:
      # dnsrr expose default port 80
      endpoint_mode: dnsrr
      
  java_app:
    image: hoojo/jib-hello:1.0
    container_name: java_app_service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    depends_on:
      - external_httpd
    environment:
      # 80 port access success, 8081/81 access failure
      #- ENV_REQUEST_URL=http://external_httpd:81/,http://external_httpd:8081/,http://external_httpd:80
      # 80 port access success, 8081/81 access failure
      #- ENV_REQUEST_URL=http://tasks.external_httpd:81/,http://tasks.external_httpd:8081/,http://tasks.external_httpd:80
  
      # access successful
      - ENV_REQUEST_URL=http://tasks.external_httpd:80
      # access successful
      - ENV_REQUEST_URL=http://tasks.ext_external_httpd:80
      # access successful
      - ENV_REQUEST_URL=http://ext_external_httpd:80
      # access successful
      - ENV_REQUEST_URL=http://external_httpd:80
          
  shell_app:
    image: busybox:latest
    container_name: shell_app_service
    tty: true
    stdin_open: true     
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    depends_on:
      - external_httpd
    environment:
      # 80 port access success, 8081/81 access failure
      #- ENV_REQUEST_URL=http://external_httpd:81/,http://external_httpd:8081/,http://external_httpd:80
      # 80 port access success, 8081/81 access failure
      #- ENV_REQUEST_URL=http://tasks.external_httpd:81/,http://tasks.external_httpd:8081/,http://tasks.external_httpd:80
      # access successful
      - ENV_REQUEST_URL=http://tasks.external_httpd:80
      # access successful
      - ENV_REQUEST_URL=http://tasks.ext_external_httpd:80
      # access successful
      - ENV_REQUEST_URL=http://ext_external_httpd:80
      # access successful
      - ENV_REQUEST_URL=http://external_httpd:80
    volumes:
      - "/mnt/docker-swarm-httpd/test-scripts:/test-scripts:ro"
    command: "sh -c ./test-scripts/test.sh"