# @changelog Added multiple docker compose file service example

version: "3"

services:
  external_httpd:
    image: httpd
    container_name: external_httpd_service
    ports:
      - 8080:80
    
  internal_httpd:
    image: httpd
    container_name: internal_httpd_service
    expose:
      - 80
    